kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: taiga-back
  namespace: {{ project_name }}
  labels:
    app: taiga-back
    template: taiga-back
  annotations:
    description: Taiga Backend Build Configuration
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'taiga-back:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.6'
      env:
        - name: PIP_INDEX_URL
  postCommit:
    script: ./manage.py test
  source:
    type: Git
    git:
      uri: 'https://github.com/msolberg/taiga-back.git'
      ref: openshift
  triggers:
    - type: ConfigChange
  runPolicy: Serial
