kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: taiga-front
  namespace: {{ project_name }}
  labels:
    app: taiga-front
    template: taiga-front
  annotations:
    description: Taiga Frontend Build Configuration
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'taiga-front:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/msolberg/taiga-front-dist.git'
      ref: master
    contextDir: dist
  triggers:
    - type: ConfigChange
  runPolicy: Serial
